### ISSUE TITLE
Add Smart CodeInsight and WebStencils

### ISSUE THREAD

**Issue by corneliusdavid** [delphidabbler/delphidabbler.github.io#162]
[Delphi 12.2](https://docwiki.embarcadero.com/RADStudio/Athens/en/12_Athens_-_Release_2) added embedded AI ([Smart CodeInsight](https://docwiki.embarcadero.com/RADStudio/Athens/en/Smart_CodeInsight)) and a new scriptable text-processing engine, [WebStencils](https://docwiki.embarcadero.com/RADStudio/Athens/en/WebStencils).

**Comment by delphidabbler** [comment]
@corneliusdavid  Thx for that - updated: see https://delphidabbler.com/notes/version-features
