### ISSUE TITLE
TWebBrowser and stopImmediatePropagation

### ISSUE THREAD

**Issue by bwdirks** [delphidabbler/delphidabbler.github.io#56]
This is not about your website. I tried to find a way to contact you but this is all I could find. The is about your article [here](https://github.com/delphidabbler/articles/blob/master/article-21.pdf). 
It appears that you have quite a bit of experience using the TWebBrowser component.
I'm trying to figure out how to use the stopImmediatePropagation function in my application. I set an OnClick event for every control on the web page. When a user clicks a checkbox, radio button or whatever, the OnClick event I created gets called 9 times. Researching this issue revealed the stopPropagation and stopImmediatePropagation functions.
But I don't know how to implement them in my code. Do you have any knowledge about this or can you direct me somewhere that might shed some light on it?

**Comment by bwdirks** [comment]
Great, thanks. And welcome back to the coding world.

 

-Barry

**Comment by delphidabbler** [comment]
Thanks - I'm slowly catching up!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
